CFLAGS += -DBOARD_BOOSTERPACK=1

CONTIKI_TARGET_DIRS += boosterpack common

BOARD_SOURCEFILES += board.c boosterpack-sensors.c leds-arch.c board-spi.c

### Signal that we can be programmed with cc2538-bsl
BOARD_SUPPORTS_BSL=1
